# Generated by Django 3.2 on 2022-11-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='preferred_os',
            field=models.CharField(choices=[(1, 'linux'), (2, 'windows'), (3, 'mac')], max_length=20),
        ),
    ]
